### ISSUE TITLE
Can you remove me from this project please !!!!

### ISSUE THREAD

**Issue by AaronNGray** [Shakyamuni177te/The-Order-of-the-Mouse#4]
Please do not do random things like this !

**Comment by Shakyamuni177te** [comment]
We do not have a democratic majority or a quorum on the issue at this point. Motion denied by the Order of the Mouse Standing Order Committee (OMSOC).

**Comment by Shakyamuni177te** [comment]
Closing this issue. Please raise a new issue if you can muster the required nominations to table a motion in the appropriate fashion.

**Comment by AaronNGray** [comment]
P.R.A.T. of the lowest denomination !

**Comment by AaronNGray** [comment]
I DONT WHAT THIS CRAP AND GAMES IN MY EMAIL INBOX REMOVE ME FROM YOUR
STUPID PROJECT

OTHERWISE I AM REPORTING YOU TO GITHUB

**Comment by Shakyamuni177te** [comment]
We understand that you are upset but we wish to leave the opportunity for contributions open and also to draw attention to our use of your preexisting code for elements of the project.

We understand that you may be reticent to be associated with 'fictional' projects or 'silly games' due to your ideological convictions, but your code is not licensed in such a way as to preclude use of the name 'AaronNGray'. If you wish to exert control over this aspect of your identity it might be best to utilize more private or less well know code repositories (as a suggestion for possible resolution here).

**Comment by Shakyamuni177te** [comment]
If you wish to involve members of the Github team in an arbitration procedure we would be more than happy to co-operate with an independent party, or parties.

**Comment by Shakyamuni177te** [comment]
Had a bit of a think and realised AaronNGray is right. Removing from repo, though we would very much like him to work on the project.
